spring:
  application:
    name: GJ-AUTH-SERVER 
  datasource:
    driver-class-name: org.postgresql.Driver
    tomcat:
      validation-query: SELECT 1
    url: jdbc:postgresql://172.16.5.46:5432/mpospaymento
    username: postgres
    password: postgres
    initialization-mode: always
  main:
    allow-bean-definition-overriding: true  
  jpa:
    hibernate:
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    properties:
      hibrenate:
       dialect: org.hibernate.dialect.PostgreSQLDialect    
       format_sql: true 
    show-sql: true 
       
check-user-scopes: false 
token-validity-minutes: 1440  